\c socialNet;

CREATE TABLE users ( 
    ID INT GENERATED BY DEFAULT AS IDENTITY, 
    Name VARCHAR(255), 
    LastName VARCHAR(255), 
    Gender VARCHAR(255), 
    DateOfBirth VARCHAR(255), 
    FriendsNum VARCHAR(255), 
    FollowersNum VARCHAR(255), 
    PRIMARY KEY (ID) 
);

CREATE TABLE cities ( 
    ID INT GENERATED BY DEFAULT AS IDENTITY, 
    Name VARCHAR(255),    
    State VARCHAR(255), 
    Country VARCHAR(255),
    Longitude VARCHAR(255), 
    Latitude VARCHAR(255), 
    PRIMARY KEY (ID) 
);

CREATE TABLE pois ( 
    ID INT GENERATED BY DEFAULT AS IDENTITY, 
    Category VARCHAR(255), 
    Longitude VARCHAR(255), 
    Latitude VARCHAR(255), 
    PRIMARY KEY (ID) 
);